[global_tags]

[agent]
  interval = "10ms"
  round_interval = true
  metric_batch_size = 5000
  metric_buffer_limit = 50000
  flush_interval = "50ms"
  hostname = "telegraf-f1"
  omit_hostname = true

# --- INFLUXDB V2 OUTPUT ---
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "f1-telemetry-secret-token"
  organization = "f1_org"
  bucket = "TelemetryData"
[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

# --- KAFKA CONSUMER INPUT ---
[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["tester1234"]
  client_id = "telegraf_f1_consumer"
  consumer_group = "influx_feeder_group"
  offset = "newest"
  max_message_len = 1000000
  
  # KORREKTUR: Muss vor den Tags deklariert werden
  data_format = "json_v2"

  [inputs.kafka_consumer.tags]
    metric = "car"

  [[inputs.kafka_consumer.json_v2]]
    measurement_name = "Formula1_measurements"
    
    [[inputs.kafka_consumer.json_v2.field]]
      path = "Vehicle\\.Speed"
      rename = "speed"
      type = "float"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "Vehicle\\.FrontLeftWingDamage"
      rename = "wingDamage_fl"
      type = "float"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "Vehicle\\.FrontRightWingDamage"
      rename = "wingDamage_fr"
      type = "float"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "Vehicle\\.Tire\\.FrontLeftWear"
      rename = "wear_fl"
      type = "float"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "Vehicle\\.Tire\\.FrontRightWear"
      rename = "wear_fr"
      type = "float"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "Vehicle\\.Tire\\.RearLeftWear"
      rename = "wear_rl"
      type = "float"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "Vehicle\\.Tire\\.RearRightWear"
      rename = "wear_rr"
      type = "float"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "Vehicle\\.LastLapTime"
      rename = "lastLapTime"
      type = "float"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "Vehicle\\.FuelLevel"
      rename = "fuel_lvl"
      type = "float"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "Vehicle\\.RPM"
      rename = "rpm"
      type = "float"