{
 "title": "Formel 1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "300ms",
 "panels": [
  {
   "title": "Panel Title",
   "type": "marcuscalidus-svg-panel",
   "gridPos": { "h": 21, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    {
     "query": "from(bucket: \"TelemetryData\")\r\n  |> range(start: -500ms, stop: 0m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Formula1_measurements\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"wear_fl\" or r[\"_field\"] == \"wear_fr\" or r[\"_field\"] == \"wear_rl\" or r[\"_field\"] == \"wear_rr\" or r[\"_field\"] == \"wingDamage_fl\" or r[\"_field\"] == \"wingDamage_fr\")\r\n  |> filter(fn: (r) => r[\"metric\"] == \"car\")\r\n  |> last()\r\n  |> aggregateWindow(every: 500ms, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TelemetryData\")\r\n  |> range(start: -1m, stop: 0m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Formula1_measurements\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> filter(fn: (r) => r[\"metric\"] == \"car\")\r\n  |> last()\r\n  |> aggregateWindow(every: 500ms, fn: last, createEmpty: false)\r\n  "
    }
   ]
  },
  {
   "title": "Fuel in Tank",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TelemetryData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Formula1_measurements\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fuel_lvl\")\r\n  |> filter(fn: (r) => r[\"metric\"] == \"car\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Last Lap Time",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"TelemetryData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Formula1_measurements\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lastLapTime\")\r\n  |> filter(fn: (r) => r[\"metric\"] == \"car\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Motor RPM",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 5, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TelemetryData\")\r\n  |> range(start: -1m, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Formula1_measurements\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rpm\")\r\n  |> filter(fn: (r) => r[\"metric\"] == \"car\")\r\n  |> aggregateWindow(every: 500ms, fn: last, createEmpty: false)\r\n"
    }
   ]
  }
 ]
}